# -*- coding: utf-8 -*-
"""
Скрипт для создания структуры папок проекта KKT
Автоматически создает все необходимые директории и файлы
"""

import os
import sys

def create_project_structure():
    """Создание полной структуры проекта"""
    
    # Получаем директорию, где находится скрипт
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    print("=" * 60)
    print("СОЗДАНИЕ СТРУКТУРЫ ПРОЕКТА KKT")
    print("=" * 60)
    print(f"\nБазовая директория: {base_dir}\n")
    
    # Список папок для создания
    directories = [
        "backend",
        "backend/api",
        "backend/utils",
        "bot",
        "scheduler",
        "frontend",
        "frontend/static",
        "frontend/static/css",
        "frontend/static/js",
        "frontend/templates",
        "database",
        "logs",
        "backups"
    ]
    
    # Файлы __init__.py для Python пакетов
    init_files = [
        "backend/__init__.py",
        "backend/api/__init__.py",
        "backend/utils/__init__.py",
        "bot/__init__.py",
        "scheduler/__init__.py"
    ]
    
    # .gitkeep для пустых папок (чтобы Git их отслеживал)
    gitkeep_folders = [
        "logs",
        "backups"
    ]
    
    created_dirs = 0
    created_files = 0
    
    # Создание папок
    print("📁 Создание папок:")
    print("-" * 60)
    for directory in directories:
        dir_path = os.path.join(base_dir, directory)
        try:
            os.makedirs(dir_path, exist_ok=True)
            print(f"  ✓ {directory}")
            created_dirs += 1
        except Exception as e:
            print(f"  ✗ {directory} - ОШИБКА: {e}")
    
    # Создание __init__.py файлов
    print("\n📄 Создание __init__.py файлов:")
    print("-" * 60)
    for init_file in init_files:
        file_path = os.path.join(base_dir, init_file)
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write("# Package initialization\n")
                f.write("# Auto-generated by create_structure.py\n")
            print(f"  ✓ {init_file}")
            created_files += 1
        except Exception as e:
            print(f"  ✗ {init_file} - ОШИБКА: {e}")
    
    # Создание .gitkeep файлов
    print("\n🔖 Создание .gitkeep файлов:")
    print("-" * 60)
    for folder in gitkeep_folders:
        gitkeep_path = os.path.join(base_dir, folder, ".gitkeep")
        try:
            with open(gitkeep_path, 'w') as f:
                f.write("")  # Пустой файл
            print(f"  ✓ {folder}/.gitkeep")
            created_files += 1
        except Exception as e:
            print(f"  ✗ {folder}/.gitkeep - ОШИБКА: {e}")
    
    # Итоговая статистика
    print("\n" + "=" * 60)
    print("РЕЗУЛЬТАТ:")
    print("=" * 60)
    print(f"✅ Создано папок: {created_dirs}")
    print(f"✅ Создано файлов: {created_files}")
    print("\n🎉 Структура проекта успешно создана!")
    print("=" * 60)
    
    # Вывод структуры дерева
    print("\n📂 Созданная структура:")
    print("-" * 60)
    display_tree(base_dir, directories)
    
    return True

def display_tree(base_dir, directories):
    """Отображение структуры папок в виде дерева"""
    tree_lines = []
    
    # Группируем по уровням
    dir_dict = {}
    for d in sorted(directories):
        parts = d.split('/')
        current = dir_dict
        for part in parts:
            if part not in current:
                current[part] = {}
            current = current[part]
    
    def print_tree(d, prefix="", is_last=True):
        items = list(d.items())
        for i, (name, sub) in enumerate(items):
            is_last_item = (i == len(items) - 1)
            connector = "└── " if is_last_item else "├── "
            print(prefix + connector + name + "/")
            
            if sub:
                extension = "    " if is_last_item else "│   "
                print_tree(sub, prefix + extension, is_last_item)
    
    print("KKT/")
    print_tree(dir_dict)

if __name__ == '__main__':
    try:
        create_project_structure()
        input("\n\nНажмите Enter для выхода...")
    except Exception as e:
        print(f"\n❌ КРИТИЧЕСКАЯ ОШИБКА: {e}")
        input("\nНажмите Enter для выхода...")
        sys.exit(1)